- name: Create a Virtual Machine in OpenShift
  hosts: all
  gather_facts: false
  vars:
    vm_name: vm1
    disk_name: additional-disk
    ns: vms
  tasks:
    - name: Hot-plug disk to running VM by using virtctl
      ansible.builtin.command: virtctl addvolume {{ vm_name }} --volume-name={{ disk_name }} --persist -n {{ ns }} --kubeconfig auth/kubeconfig

