- name: Create a Virtual Machine in OpenShift
  hosts: all
  gather_facts: false
  tasks:
    - name: Create VM by cloning an existing PVC
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            labels:
              kubevirt.io/vm: "{{ template_name }}"
            name: "{{ vm_name }}"
            namespace: "{{ project_name }}"
          spec:
            running: true
            template:
              metadata:
                labels:
                  kubevirt.io/vm: "{{ template_name }}"
              spec:
                domain:
                  devices:
                    disks:
                      - name: root-disk
                        disk:
                          bus: virtio
                        name: root-disk
                      - name: cloudinitdisk
                        disk:
                          bus: virtio
                  resources:
                    requests:
                      cpu: "{{ cpu }}"
                      memory: "{{ memory }}"
                volumes:
                  - dataVolume:
                      name: "{{ vm_name }}-c"
                    name: root-disk
                  - name: cloudinitdisk
                    cloudInitNoCloud:
                      userData: |
                        #cloud-config
                        hostname: "{{ vm_name }}.{{ base_domain }}"
                        user: "{{ username }}"
                        password: "{{ password }}"
                        chpasswd: '{ expire: False }'
                        ssh_pwauth: True
                        users:
                          - name: admin
                            sudo: "['ALL=(ALL) NOPASSWD:ALL']"
                            groups: sudo
                            shell: /bin/bash
                            passwd: 'admin@123'
            dataVolumeTemplates:
              - metadata:
                  name: "{{ vm_name }}-c"
                spec:
                  storage:
                    accessModes:
                      - ReadWriteMany
                    resources:
                      requests:
                        storage: "{{ disk_size }}"
                  source:
                    pvc:
                      namespace: "{{ project_name }}"
                      name: "{{ pvc_name }}"
      delegate_to: localhost
